### ISSUE TITLE
As a Developer, I want to remove deprecated spiders so I have an unified news crawling system

### ISSUE THREAD

**Issue by GonzaloUlla** [GonzaloUlla/unlp-dbd-newsler#11]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Only one way to run web spiders: right now this'd be `websites.py`, which applies the Template Method pattern

**Comment by GonzaloUlla** [comment]
Need confirmation of ELK stack running from @delavegamatias prior to implementation

**Comment by delavegamatias** [comment]
I will do a test run and implement this one

**Comment by pablofrias** [comment]
Is this related con scrapy_prototype folder? Remove it!
