### ISSUE TITLE
[EPIC] As a Developer I want to decouple Newsler from ELK Stack so I can change the DB seamlessly

### ISSUE THREAD

**Issue by GonzaloUlla** [GonzaloUlla/unlp-dbd-newsler#22]
**Is your feature request related to a problem? Please describe.**

- As a `DB Design` requirement, we should encapsulate and decouple from the internal ELK technical details.
- The current approach of writing a json-per-line object to a file stored in a docker volume might/should be deprecated

**Describe the solution you'd like**

Not sure yet, some decoupled framework to abstract data models and decouple CRUD operations to any persistence layer.

**Describe alternatives you've considered**

0. Use Newsler _"AS IS"_ right now, using different [Logstash output plugins](https://www.elastic.co/guide/en/logstash/current/output-plugins.html)

1. A common framework/library (set of Python modules) shared by both `news-crawler` and `twitter-crawler` components to abstract data models and decouple CRUD operations

2. `Option 1` plus a Kafka input/output mechanism (maybe a couple of new components and dependencies?)

**Additional context**
I need help, a lot.

**Comment by pablofrias** [comment]
Hi, I like pretty much Kafka option. Would be something like this?
![Decoupling_ELK_1](https://user-images.githubusercontent.com/10502906/80869008-3f0af880-8c74-11ea-8199-fb5b657776ce.png)

Other option would be to choose RDBMS as main data store and then push into Kibana. But its ugly, since the problem, in essence, is not transactional.

![Decoupling_ELK_2](https://user-images.githubusercontent.com/10502906/80869009-43371600-8c74-11ea-8142-0f123a19b79f.png)

**Comment by pablofrias** [comment]
Another option is to use Logstash outputs to CSV and implement custom mapper/ETL? to push into RDBMS.
![Decoupling_ELK_2 (1)](https://user-images.githubusercontent.com/10502906/80869188-55658400-8c75-11ea-8e1a-19d59208749b.png)

**Comment by delavegamatias** [comment]
So the filebeat approach might be easier to implement, but I think the Kafka Connect approach is more professional

**Comment by GonzaloUlla** [comment]
@pablofrias I was not thinking to include a JDBC connector nor a RDBMS anywhere actually. 
@delavegamatias agree with you. @JuliRios feel free to join the discussion

Basically, we are between 2 choices:

- [A] Keep Newsler coupled to the ELK Stack
  - Keep exporting data to a json-per-line file stored in disk
  - Use different [Logstash output plugins](https://www.elastic.co/guide/en/logstash/current/output-plugins.html) if we want to change DB
- [B] Decouple Newsler from the ELK Stack using Kafka
  - Use Kafka Connectors in both Crawlers that send JSON objects to Kafka topics
  - Develop a new component (a "Kafka Indexer") to read from Kafka topics and insert data to the chosen DB (e.g., elasticsearch, by using the ES Python library)
  - Only the "Kafka Indexer" will be couple to a specific DB library

**Comment by GonzaloUlla** [comment]
Check commit https://github.com/GonzaloUlla/unlp-dbd-newsler/commit/f66b0f72115df5b3c280e8e92590f0bbb2640178 to see how we could replace Elasticsearch with MongoDB right now

**Comment by GonzaloUlla** [comment]
We went with Kafka, check PR #32
